### ISSUE TITLE
what is the step1’s sft data format ?

### ISSUE THREAD

**Issue by txy6666yr** [wangitu/Ada-Instruct#1]
`[INST]You are expert at solving math problems that require multi-step reasoning,and here is your task: Question}[/INST]Let's think step by step.`
how to format this?

**Comment by wangitu** [comment]
If the `question` is: **"What multiple of 15 is closest to 2009?"**

And the `data_format` is: **"[INST] You are expert at solving math problems that require multi-step reasoning, and here is your task:\n{Question} [/INST] Let's think step by step."**

Then the specific data for this question becomes `data_format.format(Question=question)`, that is:
**[INST] You are expert at solving math problems that require multi-step reasoning, and here is your task:
What multiple of 15 is closest to 2009? [/INST] Let's think step by step.**

Essentially, you can customize the data format of step1. As long as the corresponding text (e.g. "[INST] You are expert at solving math problems that require multi-step reasoning, and here is your task:\n") is prepended as prompt, the generator trained on this customized data format will probably make a sound continuation of it.
